spring.data.mongodb.uri= mongodb+srv://hastiViramgama:Developer@cluster0.xn0c08q.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation= true
server.servlet.context-path=/journal
server.port = 8085
